=== NinjaCodingPK/eProject3XML/xml-resources/jaxb/flowerBind/greenhouse.xsd
<?xml version="1.0"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="greenhouse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="flower">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element name="soil">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Podzolic"/>
                            <xs:enumeration value="Dirt"/>
                            <xs:enumeration value="Sod-podzolic"/>
                        </xs:restriction>
                    </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="origin"/>
              <xs:element name="visualParameters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="stemColor">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Grey"/>
                                <xs:enumeration value="Green"/>
                                <xs:enumeration value="Yellow"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="leafColor">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Red"/>
                                <xs:enumeration value="Green"/>
                                <xs:enumeration value="Blue"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="size">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Small"/>
                                <xs:enumeration value="Big"/>
                                <xs:enumeration value="Middle"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="growingTips">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="temperature">
                        <xs:simpleType>
                            <xs:restriction base="xs:int">
                                <xs:minInclusive value="16"/>
                                <xs:maxInclusive value="28"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="lighting">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Require"/>
                                <xs:enumeration value="Not require"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:int" name="watering"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="multiplying">
                  <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Leaf"/>
                            <xs:enumeration value="Cuttings"/>
                            <xs:enumeration value="Seeds"/>
                        </xs:restriction>
                    </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NinjaCodingPK/eProject3XML/src/xml/greenhouse.xml
<?xml version="1.0" encoding="UTF-8"?>

<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="greenhouse.xsd">
    <flower id="1">
        <name>Flower1</name>
        <soil>Sod-podzolic</soil>
        <origin>Ukraine</origin>
        <visualParameters>
            <stemColor>Green</stemColor>
            <leafColor>Blue</leafColor>
            <size>Middle</size>
        </visualParameters>
        <growingTips>
            <temperature>17</temperature>
            <lighting>Require</lighting>
            <watering>3</watering>
        </growingTips>
        <multiplying>Leaf</multiplying>
    </flower>
    
    <flower id = "2">
        <name>Flower2</name>
        <soil>Podzolic</soil>
        <origin>Ukraine</origin>
        <visualParameters>
            <stemColor>Green</stemColor>
            <leafColor>Red</leafColor>
            <size>Small</size>
        </visualParameters>
        <growingTips>
            <temperature>20</temperature>
            <lighting>Not require</lighting>
            <watering>3</watering>
        </growingTips>
        <multiplying>Seeds</multiplying>
    </flower>
</greenhouse>
